// src/component/header/Header.svelte
<script>
  import { Header } from "./header";

  let data;
  const setData = (newData) => {data = newData};
  const header = new Header(setData);
</script>

<style>@import url("./header.css");</style>


<!-- svelte-ignore component-name-lowercase -->
<header class="header flex-col" style={`zoom: ${data.zoom}`}>
  <div>
    <img src={data.appIcon} alt="Tool Logo" />
    <span>Game Color Helper Tool</span>
  </div>
</header>

// src/components/header/HeaderComponent.jsx
import React from 'react';

import "./Header.css";


const HeaderComponent = (props) =>
{
	let logoTitle = "Pretty Soldier Sailor Moon Editor (Arcade)";
			
	return (
		<header
			className="header colLinedFlex"
			style={{zoom: props.zoom}}
		>
			<div>
				<img src="src/images/base/gchp_icon.png" />
				<label>Game Color Helper Tool</label>
			</div>
		</header>
	);
}


export default HeaderComponent;
